# 0. Importing Modules

코드의 기본은 해당 코드를 작성할 때 필요한 module들을 가져오는 것부터 시작됩니다.

In [1]:
# 과제를 시작하기 전 이 셀을 무조건 실행하세요.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as DT
import matplotlib.dates as date2num

# 아래에 필요한 것들을 추가로 작성해주세요.

# 1.Numpy

## 1.1 Numpy 알아보기

### 1.1.1 numpy에 대한 간단한 설명을 적어주세요.

다차원 배열,행렬 연산을 효율적으로 처리하고 사용할 수 있는 함수와 메소드를 제공하는 패키지

### 1.1.2 본인의 numpy version을 출력해주세요

In [ ]:
! pip --version numpy

pip 24.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)


##1.2 numpy array
* 1.2의 문제들은 모두 코드 한 줄로 적어야 합니다.
* '#이곳에 작성'을 지우고 코드를 적어주세요.

###1.2.1 숫자 0부터 9까지 숫자로 이루어진 numpy array를 하나 만드시오.

In [8]:
arr = np.array([0,1,2,3,4,5,6,7,8,9]) #이곳에 작성
print(arr)

[0 1 2 3 4 5 6 7 8 9]


###1.2.2 위의 문제에서 만든 arr의 요소 중 홀수인 수를 모두 10으로 변경하시오.

In [9]:
no_odd = np.array([])  #이곳에 작성
for i in arr:
    if i%2==1:
        no_odd = np.append(no_odd, 10)
    else:
        no_odd = np.append(no_odd, i)

print(no_odd)

[ 0. 10.  2. 10.  4. 10.  6. 10.  8. 10.]


###1.2.3 위의 문제에서 만든 arr는 1차원 배열입니다. 이 배열을 2차원 배열로 변경하시오.
array([0,1,2,3,4,5,6,7,8,9]) -> array([[0,1,2,3,4],[5,6,7,8,9]])

In [11]:
arr_2d = arr.reshape((2,5))#이곳에 작성
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


###1.2.4 True로 이루어진 3x3 numpy array를 만드시오.

In [13]:
true_mat = np.array([True]*9).reshape(3,3) #이곳에 작성
print(true_mat)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


###1.2.5 숫자 0부터 8까지로 이루어진 3x3 numpy array를 만드시오.

In [5]:
mat = np.array(range(0,9)).reshape(3,3) #이곳에 작성
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


###1.2.6 숫자 5부터 10까지의 난수로 이루어진 array를 만드시오.

In [9]:
rand_arr = np.random.randint(5,11,(1,8))#이곳에 작성
print(rand_arr)

[[10 10  7  9  5  6  9  7]]


###1.2.7 위의 1.2.5번 문제에서 만든 mat의 모든 행들을 역으로 작성하세요.
array([0,1,2],[3,4,5],[6,7,8]]) -> array([2,1,0],[5,4,3],[8,7,6]])

In [10]:
reverse_mat = mat.transpose() #이곳에 작성
print(reverse_mat)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


## 1.3 numpy를 이용한 data 처리

###1.3.1 iris_1d는 꽃잎 길이와 종에 대한 data입니다. 해당 데이터의 앞에서 10개의 data만 출력하시오.
* iris_1d 변수의 내용을 변경하지 마시오.

In [20]:
# 해당 셀을 실행하되 수정하지 마세요.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
np.random.seed(10)
np.random.shuffle(iris_1d)
iris_1d

<ipython-input-20-e6a34f2d108b>:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([(6.3, 2.3, 4.4, 1.3, b'Iris-versicolor'),
       (6.4, 2.7, 5.3, 1.9, b'Iris-virginica'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (6.1, 3. , 4.6, 1.4, b'Iris-versicolor'),
       (5. , 3.3, 1.4, 0.2, b'Iris-setosa'),
       (5. , 2. , 3.5, 1. , b'Iris-versicolor'),
       (6.3, 2.5, 4.9, 1.5, b'Iris-versicolor'),
       (5.8, 2.7, 4.1, 1. , b'Iris-versicolor'),
       (5.1, 3.4, 1.5, 0.2, b'Iris-setosa'),
       (5.7, 2.8, 4.5, 1.3, b'Iris-versicolor'),
       (5.6, 3. , 4.5, 1.5, b'Iris-versicolor'),
       (5.8, 2.7, 5.1, 1.9, b'Iris-virginica'),
       (5.5, 2.3, 4. , 1.3, b'Iris-versicolor'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (6.8, 3. , 5.5, 2.1, b'Iris-virginica'),
       (6. , 3.4, 4.5, 1.6, b'Iris-versicolor'),
       (4.4, 3. , 1.3, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (5. , 3.2, 1.2, 0.2, b'Iris-setosa'),
       (7.1, 3. , 5.9, 2.1, b'Iris-virginica'),
       

In [33]:
iris_1d[:10]

array([(6.3, 2.3, 4.4, 1.3, b'Iris-versicolor'),
       (6.4, 2.7, 5.3, 1.9, b'Iris-virginica'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (6.1, 3. , 4.6, 1.4, b'Iris-versicolor'),
       (5. , 3.3, 1.4, 0.2, b'Iris-setosa'),
       (5. , 2. , 3.5, 1. , b'Iris-versicolor'),
       (6.3, 2.5, 4.9, 1.5, b'Iris-versicolor'),
       (5.8, 2.7, 4.1, 1. , b'Iris-versicolor'),
       (5.1, 3.4, 1.5, 0.2, b'Iris-setosa'),
       (5.7, 2.8, 4.5, 1.3, b'Iris-versicolor')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

###1.3.2 iris data는 4개의 숫자 데이터(꽃잎의 길이)와 1개의 문자 데이터(꽃의 종)로 이루어져 있습니다. 위 문제에서의 iris10 데이터의 종 정보만 출력하시오.


In [42]:
iris10 = iris_1d[:10]
# iris10[[:4]]
# 요소 속의 데이터를 추출하는 법을 모르겠음

# 해결
iris10[['f0', 'f1', 'f2', 'f3']]

array([(6.3, 2.3, 4.4, 1.3), (6.4, 2.7, 5.3, 1.9), (5.4, 3.7, 1.5, 0.2),
       (6.1, 3. , 4.6, 1.4), (5. , 3.3, 1.4, 0.2), (5. , 2. , 3.5, 1. ),
       (6.3, 2.5, 4.9, 1.5), (5.8, 2.7, 4.1, 1. ), (5.1, 3.4, 1.5, 0.2),
       (5.7, 2.8, 4.5, 1.3)],
      dtype={'names': ['f0', 'f1', 'f2', 'f3'], 'formats': ['<f8', '<f8', '<f8', '<f8'], 'offsets': [0, 8, 16, 24], 'itemsize': 47})

In [55]:
iris_1d[:30][['f0']]

array([(6.3,), (6.4,), (5.4,), (6.1,), (5. ,), (5. ,), (6.3,), (5.8,),
       (5.1,), (5.7,), (5.6,), (5.8,), (5.5,), (4.9,), (5.1,), (6.8,),
       (6. ,), (4.4,), (5.1,), (5. ,), (7.1,), (6.4,), (6.2,), (4.8,),
       (5.9,), (4.7,), (5.7,), (5.5,), (6.8,), (7.7,)],
      dtype={'names': ['f0'], 'formats': ['<f8'], 'offsets': [0], 'itemsize': 47})

### 1.3.3 iris_1d data의 앞에서 30개의 data만 추출하여 첫 번째 요소의 길이가 5.0 이하인 것만 출력하시오.

In [58]:
iris_30 = iris_1d[:30]
iris_30[0][['f0']]

(6.3,)

In [61]:
for i in iris_30:
    if iris_30[i][['f0']] <= 5.0:
        print(iris_30[i])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [62]:
# 해결
# i가 이미 행에 접근한 것이므로 이후 불필요한 인덱싱 생략
for i in iris_30:
    if i['f0'] <= 5.0:
        print(i)

(5., 3.3, 1.4, 0.2, b'Iris-setosa')
(5., 2., 3.5, 1., b'Iris-versicolor')
(4.9, 3., 1.4, 0.2, b'Iris-setosa')
(4.4, 3., 1.3, 0.2, b'Iris-setosa')
(5., 3.2, 1.2, 0.2, b'Iris-setosa')
(4.8, 3.4, 1.9, 0.2, b'Iris-setosa')
(4.7, 3.2, 1.3, 0.2, b'Iris-setosa')


### 1.3.4 irids_1d data의 앞에서 15개의 data만 추출하여 첫 번째 요소와 네 번째 요소 간의 상관관계를 출력하시오.

###1.3.5 iris_1d 데이터에서 각 종별로 개수가 몇 개인지 출력하시오.

###1.3.6 iris_1d 데이터 중 3번째 요소의 길이가 5.0 이상인 data의 index를 모두 출력하시오.

##1.4

###1.4.1 0부터 1까지의 랜덤 숫자 100개로 이루어진 array를 하나 만들고 array의 평균, 분산, 표준편차, 중앙값을 출력하시오.

###1.4.2 iris_2d 데이터의 첫 번째 열과 3번째 열의 값들 간의 상관계수를 출력하시오. (iris_2d 변수의 내용을 수정하지 마시오.)

In [ ]:
# 해당 셀을 실행만 하되 수정하지 마세요.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

###1.4.3 0부터 10까지의 랜덤한 정수 100개로 이루어진 array를 하나 만들고 가장 빈도수가 많은 숫자를 출력하시오. (만약 빈도수가 같은 숫자가 있다면 모두 출력하시오.)

### 1.4.4 numpy의 내장 함수를 이용해 현재 시간을 출력하시오. (출력 형식은 자유이고 연,월,일,시,분,초를 모두 출력해야함)

### 1.4.5 numpy의 내장 함수를 이용해 2024년 9월 1일부터 2024년 9월 20일까지의 날짜들 중 홀수일로만 이루어진 array를 하나 만들고 출력하시오.

In [ ]:
# 예시 - 2018년 2월 1일부터 2018년 2월 23일까지

# ['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
#  '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
#  '2018-02-21' '2018-02-23']

# 2. Pandas

## 2.1 Pandas 알아보기

### 2.1.1 Pandas에 대한 간단한 설명을 적어주세요.

데이터 전처리 또는 분석에 유용한 파이썬 라이브러리

### 2.1.2 본인의 Pandas version을 출력해주세요.

In [63]:
! pip --version pandas

pip 24.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)


## 2.2 pandas 자료구조

### 2.2.1 pandas의 series와 numpy array의 차이점을 쓰시오.

### 2.2.2  알파벳  a-z로 이루어진 series를 하나 만들고 출력하시오.

In [2]:
a = pd.Series([chr(i) for i in range(97,123)])
print(a)

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


### 2.2.3 list1 = [2,4,6,8,10], list2 = [3,6,9,12]일 때 각 리스트를 series1, series2로 바꾼 뒤 series1과 series2를 출력하시오.

In [3]:
list1 = [2,4,6,8,10]
list2 = [3,6,9,12]
series1 = pd.Series(list1)
series2 = pd.Series(list2)
print(series1)
print(series2)

0     2
1     4
2     6
3     8
4    10
dtype: int64
0     3
1     6
2     9
3    12
dtype: int64


### 2.2.4 1부터 5까지의 정수로 이루어진 series와 6부터 10까지의 정수로 이루어진 series를 만들어 각각을 열(column)로 가지는 dataframe을 만들고 출력하시오. (2개의 열을 가지는 dataframe 출력)

In [ ]:
# 예시
#   0 1
# 0 1 6
# 1 2 7
# 2 3 8
# 3 4 9
# 4 5 10

In [12]:
a = pd.Series([1,2,3,4,5])
b = pd.Series([6,7,8,9,10])
all = pd.concat([a,b], axis=1)    # axis=1 설정하여 오른쪽으로 추가
df = pd.DataFrame(all)
df

0   1
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

### 2.2.5 1-3 정수, 4-6 정수, 7-9 정수, 10-12 정수로 이루어진 series를 만들어 각각을 행(row)으로 가지는 dataframe을 만들고 출력하시오. (4개의 행을 가지는 dataframe 출력)

In [ ]:
# 예시
#    0  1  2
# 0  1  2  3
# 1  4  5  6
# 2  7  8  9
# 3 10 11 12

In [19]:
a = pd.Series([1,2,3])
b = pd.Series([4,5,6])
c = pd.Series([7,8,9])
d = pd.Series([10,11,12])
df = pd.DataFrame([a,b,c,d])
df

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

### 2.2.6 2.2.5에서 만든 dataframe의 index를 ['one','two','three','four']으로 바꾸고 출력하시오.

In [21]:
df.index = ['one', 'two', 'three', 'four']
df

0   1   2
one     1   2   3
two     4   5   6
three   7   8   9
four   10  11  12

### 2.2.7
*  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
*  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

위 두 리스트를 series로 변환하고 ***원소별로 더한 값을 새로운 series로 만들어*** 출력하시오. (진한 글씨로 나타낸 부분은 한 줄로 작성)



In [ ]:
# 실행하지 마시오.
s1 = [1,2,3]
s2 = [3,2,1]

In [24]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list2 = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
se1 = pd.Series(list1)
se2 = pd.Series(list2)
sum = se1 + se2
sum

0    11
1    11
2    11
3    11
4    11
5    11
6    11
7    11
8    11
9    11
dtype: int64

### 2.2.8 numpy의 함수를 이용하여 아래와 같은 출력을 만드시오.

In [ ]:
# 예시
# 2000-01-01     1.0
# 2000-01-03    10.0
# 2000-01-05     3.0
# 2000-01-07     NaN

In [25]:
list = [[2000-01-01, 1.0], [2000-01-03, 10.0], [2000-01-05, 3.0], [2000-01-07, NaN]]
a = np.array(list)
a

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (<ipython-input-25-62f01d40aa20>, line 1)

In [31]:
# 해결
dates = ['2000-01-01', '2000-01-03', '2000-01-05', '2000-01-07']
arr = np.array([1.0, 10.0, 3.0, np.nan])
se = pd.Series(arr, index=dates)
print(se)

2000-01-01     1.0
2000-01-03    10.0
2000-01-05     3.0
2000-01-07     NaN
dtype: float64


## 2.3

### 2.3.1 아래 path에 해당하는 경로의 csv 파일을 읽고 그 내용을 cars93 이라는 변수로 저장한 뒤 출력하시오.

**cars93 변수의 내용을 변경하지 마시오.**

In [27]:
# 해당 셀을 실행하되 수정하지 마세요.
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'

In [28]:
cars93 = pd.read_csv(path) # 이곳에 이어서 작성하세요.
cars93

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

### 2.3.2 위에서 cars93 데이터의 요약을 출력하시오.

In [29]:
cars93.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

### 2.3.3 cars93에서 price가 가장 높은 제품의 manufacturer을 출력하시오.

In [34]:
cars93['Price'].max()

61.9

### 2.3.4 cars93에서 'Type'열의 이름을 'CarType'으로 바꾸고 Renamed라는 이름의 변수에 저장한 뒤 출력하시오.

In [35]:
Renamed = cars93.rename(columns={'Type':'CarType'})
Renamed

Manufacturer    Model  CarType  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

### 2.3.5 Renamed의 모든 열의 내용중 '.'을 '_'으로 바꾼뒤 Renamed를 출력하시오. (반복문 외의 다른 방법을 사용하시오)

**예시**

* Min.Price -> Min_Price
* MPG.city -> MPG_city

### 2.3.6 아래 missing_path는 결측치가 데이터로 해당 경로의 csv 파일을 열어 결측치를 확인하고 그 개수를 출력하시오.

In [ ]:
# 해당 셀을 실행하되 수정하지 마세요.
missing_path = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'

### 2.3.7 위의 데이터 중 결측치가 가장 많은 열을 출력하시오.

### 2.3.8 정수 1부터 20까지로 이루어진 series를 만들고 4x5 크기의 dataframe으로 변형한 뒤 출력하시오. 그리고 해당 dataframe의 2,3번째 열만 출력하시오.

### 2.3.9 문제 2.3.8에서 만든 dataframe의 열을 알파벳 순으로('a','b','c',...) 열 이름을 변경하고 a열과 c열만 출력하시오.

# 3. Matplotlib

## 3.1 Matplotlib 알아보기

###3.1.1 matplotlib의 pyplot libraby에 대한 간단한 설명을 적어주세요.

### 3.1.2 본인의 matplotlib.pyplot의 version을 출력하시오.

## 3.2

### 3.2.1 아래의 조건에 맞추어 주어진 데이터 X,Y의 값에 대한 꺽은선 그래프를 그리시오.

1. x,y축의 이름을 붙이시오.
2. 그래프의 제목은 'Line'이라고 붙이시오.
3. 그래프의 선 색을 빨간색으로 하시오.
4. x축의 눈금은 5단위로 표시하시오.

In [ ]:
# 해당 셀을 실행하되 수정하지 마시오.
X = range(1, 50)
Y = [value * 3 for value in X]

### 3.2.2 아래의 조건에 맞추어 주어진 데이터에 대한 꺽은선 그래프를 그리시오.

1. 첫 번째 그래프의 선 색은 빨강, 두 번째 선 색은 초록으로 하시오.
2. 그래프의 제목은 'Two Lines'로 하시오.
3. 선의 굵기를 4로 통일하시오.
4. 각 선의 색에 따라 빨강 색은 'line1', 파랑 색은 'line2'임을 나타내는 표시를 그래프에 넣으시오.
5. 첫 번째 그래프의 점은 삼각형, 두 번째 그래프의 점은 원형으로 그리시오.

In [ ]:
# 해당 셀의 내용을 수정하지 마시오.
# line 1 points
x1 = [10,20,30]
y1 = [20,40,10]

# line 2 points
x2 = [10,20,30]
y2 = [40,10,30]

### 3.2.3 주어진 데이터에서 x는 프로그래밍 언어, popularity는 프로그래밍의 선호도이다. 프로그래밍 언어에 따른 선호도에 대한 막대그래프를 아래 조건에 맞추어 그리시오.

1. X축의 이름은 'Programming Language'로 하시오.
2. Y축의 이름은 'Popularity'로 하시오.
3. 격자 무늬를 넣으시오.
4. 그래프의 제목은 'Popularity of programming language'로 하시오.
5. X축의 눈금을 표시하시오.
6. 막대그래프는 중간맞춤으로 그리시오.

In [ ]:
# 해당 셀을 실행하되 수정하지 마시오.
x = ['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++']
popularity = [22.2, 17.6, 8.8, 8, 7.7, 6.7]

### 3.2.4 아래 조건에 맞추어 주어진 두 데이터에 대한 꺽은선 그래프 두 개를 한 번에 그리시오.

1. data1의 그래프는 왼쪽에 data2의 그래프는 오른쪽에 그리시오.
2. data1의 그래프는 실선, data2의 그래프는 점선으로 그리시오.
3. 각각의 그래프의 최댓값에 화살표 표시를 넣고 'maximum'임을 표시하시오.
4. 각 그래프 별로 'data1', 'data2'라는 제목을 붙이시오.


In [ ]:
# 해당 셀을 실행하되 수정하지 마시오.
# data1
x1 = [i for i in range(10)]
y1 = [i*i+3 for i in x1]

# data2
x2 = [i for i in range(-5,6)]
y2 = [(-1)*i*i+25 for i in x2]